use_frameworks!

platform :ios, '10.0'

target 'BISegmentedControl_Example' do
  pod 'BISegmentedControl', :path => '../'

  target 'BISegmentedControl_Tests' do
    inherit! :search_paths

    
  end
end
